package com.eviro.assessment.grad001.pardonandmabasa.service;

import com.eviro.assessment.grad001.pardonandmabasa.entity.AccountProfile;
import com.eviro.assessment.grad001.pardonandmabasa.repository.AccountProfileRepository;
import org.springframework.core.io.FileSystemResource;
import org.springframework.stereotype.Service;
import org.springframework.web.multipart.MultipartFile;

import java.io.File;
import java.io.IOException;
import java.net.URI;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.Base64;

@Service
public class FileParserServiceImpl implements FileParser {

    private final AccountProfileRepository accountProfileRepository;

    public FileParserServiceImpl(AccountProfileRepository accountProfileRepository) {
        this.accountProfileRepository = accountProfileRepository;
    }

    @Override
    public void parseCSV(MultipartFile csvFile) {
        // Implement CSV parsing logic and extract data to save as AccountProfile objects
    }

    @Override
    public File convertCSDataToImage(String base64ImageData) throws IOException {
        byte[] imageData = Base64.getDecoder().decode(base64ImageData);
        File imageFile = new File("image.jpg"); // You can modify the file name as per your requirements
        Files.write(Paths.get(imageFile.getPath()), imageData);
        return imageFile;
    }

    @Override
    public URI createImageLink(File fileImage) {
       
        // link will be generated by the ImageController endpoint
        return fileImage.toURI();
    }
}
